# Generated by Django 3.2.8 on 2021-10-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Makale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yazar', models.CharField(max_length=50)),
                ('baslik', models.CharField(max_length=50)),
                ('metin', models.TextField()),
                ('sehir', models.CharField(max_length=50)),
                ('yaratilma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('aktif', models.BooleanField()),
                ('guncellenme_tarihi', models.DateTimeField()),
            ],
        ),
    ]
